import type {
  AttractorResults,
  ComputationModes,
  ComputationStatus,
  ControlResults,
  DecisionsTSSD,
  NodeDataTSSD,
} from '../../../types/types';
import type { LiveModelInt } from '../LiveModel/LiveModelInt';
import type { AttractorAnalysisInt } from './AttractorAnalysis/AttractorAnalysisInt';
import type { ControlInt } from './Control/ControlInt';
import type { ModelInt } from './Model/ModelInt';

/**
 * Interface for ComputationManagerClass. All public functions are included with their documentation and types.
 * Types are kept as in the class, even if there are syntax errors due to dependencies.
 */
export interface ComputationManagerInt {
  // #region --- Modules ---

  /** Module responsible for running computation of control and setting of parameters needed for this computation. */
  Control: ControlInt;

  /** Module responsible for performing attractor analysis computation and visualization of its results */
  AttractorAnalysis: AttractorAnalysisInt;

  /** Module responsible for performing operations over models (eg. validation of models update functions) */
  Model: ModelInt;

  // #endregion

  // #region --- LiveModel Reference ---

  /** Setter for the LiveModel reference */
  setLiveModel(liveModel: LiveModelInt): void;

  // #endregion

  // #region --- External Compute Engine Adress Setters/Getters ---

  /** Sets the URL of the compute engine */
  setComputeEngineAddress(address: string): void;

  /** Returns the URL of the compute engine */
  getComputeEngineAddress(): string | undefined;

  // #endregion

  // #region --- Connection Manager ---

  isComputeEngineConnected(): boolean;

  toggleConnection(): void;

  computationIsRunning(): boolean;

  // #endregion

  // #region --- Computation Status ---

  setComputationStatus(
    warning: string | undefined,
    error: string | undefined,
    computeEngineStatus?: string | undefined,
    computationStatus?: ComputationStatus | undefined,
    color?: string | undefined
  ): void;

  // #endregion

  // #region --- Trap Space Succession Diagram ---

  /** Fetches succession diagram for the  */
  getTrapSpaceSuccessionDiagram(
    insertSuccessionDiagramFunction: (nodes: NodeDataTSSD[]) => void
  ): void;

  getDecisionsTSSD(
    nodeId: number,
    setDecisionsFunction: (decisions: DecisionsTSSD) => void
  ): void;

  /** Extends trap space succession diagram with a new node defined by decisionId.
   * The new node is a child of the node with id = nodeId. The new node is inserted into the succession diagram using the insertSuccessionDiagramFunction.
   * @param nodeId - (number) ID of the parent node from which the new node will be generated by applying the decision with ID = decisionId.
   * @param decisionId - (number) ID of the decision which will be applied to generate a new node in the trap space succession diagram.
   * @param insertSuccessionDiagramFunction - (function) Function which takes a list of NodeDataTSSD and inserts them into the succession diagram visualization. This function is used to insert the new node into the visualization after it is generated.
   */
  makeDecisionTSSD(
    nodeId: number,
    decisionId: number,
    insertSuccessionDiagramFunction: (nodes: NodeDataTSSD[]) => void
  ): void;

  /** Deletes decision from trap space succession diagram.
   *  @param nodeId - (number) ID of the node from which the decision will be deleted.
   *  @param removeNodesFromVisualizationFunction - (function) Function which takes a node and a list of removed node IDs. This function is used to remove the deleted node and its child nodes from the visualization after they are deleted.
   */
  deleteDecisionTSSD(
    nodeId: number,
    removeNodesFromVisualizationFunction: (
      node: NodeDataTSSD,
      removedNodes: number[]
    ) => void
  ): void;

  // #endregion

  // #region --- Results ---

  setResults(
    warning: string | undefined,
    error: string | undefined,
    type: ComputationModes | undefined,
    results: AttractorResults | ControlResults | undefined
  ): void;

  // #endregion
}
