import type {
  DecisionsTSSD,
  NodeDataTSSD,
  NodeDataTSSDWithMotifs,
} from '../../../../types/types';

export interface TrapSpaceSuccessionDiagramInt {
  // #region --- Trap Space Succession Diagram ---

  /** Fetches succession diagram for the  */
  getTrapSpaceSuccessionDiagram(
    insertSuccessionDiagramFunction: (nodes: NodeDataTSSDWithMotifs[]) => void
  ): void;

  getDecisionsTSSD(
    nodeId: number,
    setDecisionsFunction: (decisions: DecisionsTSSD) => void
  ): void;

  /** Extends trap space succession diagram with a new node defined by decisionId.
   * The new node is a child of the node with id = nodeId. The new node is inserted into the succession diagram using the insertSuccessionDiagramFunction.
   * @param nodeId - (number) ID of the parent node from which the new node will be generated by applying the decision with ID = decisionId.
   * @param decisionId - (number) ID of the decision which will be applied to generate a new node in the trap space succession diagram.
   * @param insertSuccessionDiagramFunction - (function) Function which takes a node NodeDataTSSD and insert it into the succession diagram visualization. This function is used to insert the new node into the visualization after it is generated.
   */
  makeDecisionTSSD(
    nodeId: number,
    decisionId: number,
    insertSuccessionDiagramFunction: (node: NodeDataTSSD) => void
  ): void;

  /** Deletes decision from trap space succession diagram.
   *  @param node - (NodeDataTSSD) node from which the decision will be deleted.
   *  @param removeNodesFromVisualizationFunction - (function) Function which takes a node and a list of removed node IDs. This function is used to remove the deleted node and its child nodes from the visualization after they are deleted.
   */
  deleteDecisionTSSD(
    node: NodeDataTSSDWithMotifs,
    removeNodesFromVisualizationFunction: (
      node: NodeDataTSSDWithMotifs,
      removedNodes: number[]
    ) => void
  ): void;

  // #endregion
}
