import type {
  ComputationStatus,
  DecisionsTSSD,
  NodeDataTSSD,
  NodeDataTSSDWithMotifs,
} from '../../../../types/types';

/** Compute Engine module which contains function used for computing and working with Trap Space Succession Diagram. */
export interface TrapSpaceSuccessionDiagramInt {
  // #region --- Computation ---

  /**
   * Initiates a computation based on the provided Boolean network model.
   * This method sends a request to start an "Trap Space" calculation using the specified model.
   *
   * @param model The Boolean network model in Aeon string format.
   * @param callback An optional function to be called upon completion or error of the computation.
   *                 If provided, it receives:
   *                 - `warning`: Any warning messages generated during the process.
   *                 - `error`: Error message if the computation failed.
   *                 - `engineStatus`: Current status of the background processing engine.
   *                 - `compStatus`: Detailed status of the specific computation job.
   *                 - `color`: Visual indicator color associated with the current state (e.g., green for success).
   * @result Triggers a request to the backend and updates the internal waiting state before asynchronous resolution.
   */
  startComputation(
    model: string,
    callback:
      | ((
          warning: string | undefined,
          error: string | undefined,
          engineStatus: string | undefined,
          compStatus: ComputationStatus | undefined,
          color: string | undefined
        ) => void)
      | undefined
  ): void;

  // #ednregion

  // #region --- Diagram Operations ---

  /** Gets the trap space succession diagram for a specific model. */
  getTrapSpaceSuccessionDiagram(
    model: string,
    callback: (
      error: string | undefined,
      nodes: NodeDataTSSDWithMotifs[] | undefined
    ) => void
  ): void;

  /** Gets decisions for a specific node in the Trap Space Succession Diagram.
   *  @param nodeId - (number) The ID of the node to fetch decisions for.
   *  @param callback - (function) Function which takes a list of decisions and sets them in the Trap Space Succession Diagram page. This function is used to set the available decisions for a node after they are fetched.
   */
  getDecisionsTSSD(
    nodeId: number,
    callback: (
      error: string | undefined,
      decisions: DecisionsTSSD | undefined
    ) => void
  ): void;

  /** Extends trap space succession diagram with a new node defined by decisionId.
   * The new node is a child of the node with id = nodeId. The new node is inserted into the succession diagram using the insertSuccessionDiagramFunction.
   * @param nodeId - (number) ID of the parent node from which the new node will be generated by applying the decision with ID = decisionId.
   * @param decisionId - (number) ID of the decision which will be applied to generate a new node in the trap space succession diagram.
   * @param callback - (function) Function which takes node NodeDataTSSD and inserts it into the succession diagram visualization. This function is used to insert the new node into the visualization after it is generated.
   */
  makeDecisionTSSD(
    nodeId: number,
    decisionId: number,
    callback: (
      error: string | undefined,
      node: NodeDataTSSD | undefined
    ) => void
  ): void;

  /** Deletes decision from trap space succession diagram.
   *  @param node - (NodeDataTSSD) node from which the decision will be deleted.
   *  @param callback - (function) Function which takes a node and a list of removed node IDs. This function is used to remove the deleted node and its child nodes from the visualization after they are deleted.
   */
  deleteDecisionTSSD(
    node: NodeDataTSSDWithMotifs,
    callback: (
      error: string | undefined,
      node: NodeDataTSSDWithMotifs | undefined,
      removedNodes: number[]
    ) => void
  ): void;

  // #endregion
}
