export type InputWithButtonProps = {
  /** Height of the component – any valid CSS width value (e.g. "95%" or "300px"). (26px by default) */
  componentHeight?: string;
  /** Width of the component – any valid CSS width value (e.g. "95%" or "300px"). (100% by default)*/
  componentWidth?: string;

  /** Colour used for the text inside the input. */
  textColor: string;
  /** Background colour of the input element. */
  inputColor: string;
  /** Border colour of the input element. */
  inputBorderColor: string;
  /** Height of the input – any valid CSS width value (e.g. "95%" or "300px"). (100% by default) */
  inputHeight?: string;
  /** Width of the input – any valid CSS width value (e.g. "95%" or "300px"). (80% by default)*/
  inputWidth?: string;
  /** Function which shows tooltip for the input. */
  inputTooltipFunction?: (e: MouseEvent) => void;
  /** Placeholder text shown when the input is empty. */
  placeholder?: string;
  /**
   * Callback that receives the new value whenever the user types.
   * Usually you’ll pass a `setState` function generated by `useState`.
   */
  onWrite?: (newValue: string) => void;
  /**
   * Optional callback invoked when the user submits the input
   * (e.g., presses the Enter key). Receives the current value as an argument.
   */
  onSubmit?: (newValue: string) => void;

  /** Size of the button (button is always square) – any valid CSS (e.g. "32px", "2rem", "3%") -> % is computed from the componentHeight (100% by default) */
  buttonSize?: string;
  /** URL, SVG, or font‑awesome class for the icon that appears inside the button.
   *  Example: "/icons/search.svg" | "fa-solid fa-magnifying-glass" */
  buttonIcon?: string;
  /** Background colour of the button (normal state). */
  buttonColor: string;
  /** Background colour of the button when the mouse hovers over it. */
  buttonHoverColor: string;
  /** Function which shows tooltip for the button. */
  buttonTooltipFunction?: (e: MouseEvent) => void;
  /**
   * Optional callback invoked when an associated button inside the
   * component is clicked (e.g., a search icon or clear button).
   */
  onButtonClick?: (newValue: string) => void;

  /** Function which hides tooltip after element (input/button) is not hovered. */
  clearTooltipFunction?: () => void;

  /** Current value of the controlled input. */
  value: string;
};
